# Load converted Sigma rules from JSON file generated by convert_sigma_rules.py
locals {
  converted_rules_file = "${path.module}/converted_rules.json"
  converted_rules      = fileexists(local.converted_rules_file) ? jsondecode(file(local.converted_rules_file)) : {}
}

# Deploy the Okta admin role assignment detection rule from Sigma
module "rule_okta_administrator_role_assigned_to_non_admin_user_account_sigma" {
  count = contains(keys(local.converted_rules), "okta_administrator_role_assigned_to_non_admin_user_account") ? 1 : 0

  source               = "./modules/sumo_monitor"
  standard_name        = "Administrator Role Assigned to Non-Admin User Account (Sigma)"
  standard_description = "Identifies when an administrator role is assigned to a non-admin Okta user account i.e. a standard user account that does not follow our company's admin account naming conventions. Investigate using playbook PB-100."
  standard_query       = local.converted_rules["okta_administrator_role_assigned_to_non_admin_user_account"]["query"]
  standard_folder      = sumologic_monitor_folder.detections.id
  tines_webhook        = length(sumologic_connection.tines_webhook) > 0 ? sumologic_connection.tines_webhook[0].id : null
  tines_webhook_override = <<EOF
{
  "rule.name": "{{Name}}",
  "rule.description": "{{Description}}",
  "query.url": "{{QueryURL}}",
  "query": "{{Query}}",
  "trigger.range": "{{TriggerTimeRange}}",
  "trigger.name": "{{TriggerTime}}",
  "alert.payload": "{{ResultsJson}}"
}
EOF
}
