# Load converted Sigma rules from JSON file generated by convert_sigma_rules.py
locals {
  converted_rules_file = "${path.module}/converted_rules.json"
  converted_rules      = fileexists(local.converted_rules_file) ? jsondecode(file(local.converted_rules_file)) : {}

  # Helper to safely get a rule query
  okta_admin_role_rule_exists = fileexists(local.converted_rules_file) && lookup(local.converted_rules, "okta_administrator_role_assigned_to_non_admin_user_account", null) != null
  okta_admin_role_query       = local.okta_admin_role_rule_exists ? local.converted_rules["okta_administrator_role_assigned_to_non_admin_user_account"]["query"] : ""
}

# Deploy the Okta admin role assignment detection rule from Sigma
module "rule_okta_administrator_role_assigned_to_non_admin_user_account_sigma" {
  count = local.okta_admin_role_rule_exists ? 1 : 0

  source               = "./modules/splunk_savedsearch"
  standard_name        = "Administrator Role Assigned to Non-Admin User Account (Sigma)"
  standard_description = "Identifies when an administrator role is assigned to a non-admin Okta user account i.e. a standard user account that does not follow our company's admin account naming conventions. Investigate using playbook PB-100."
  standard_query       = local.okta_admin_role_query
  app_name             = splunk_apps_local.detections.name
  cron_schedule        = "*/5 * * * *" # Every 5 minutes
  earliest_time        = "-1h@h"       # 1 hour ago
  latest_time          = "now"
}
